name: 'dart publish setup'
description: 'This action will setup and publish m3o-dart clients'

inputs:
  pub_credentials: 
    description: 'dart pub.dev credentials'
    required: true

outputs:
  success:
    description: 'The result of this Action'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pub_credentials }}